import { Exercise } from '../types';

export const EXERCISE_LIBRARY: Omit<Exercise, 'isCustom' | 'createdAt'>[] = [
  // ─── Chest ─────────────────────────────────────────────────────────────────
  { id: 'bench-press', name: 'Barbell Bench Press', primaryMuscles: ['chest'], secondaryMuscles: ['shoulders', 'triceps'], equipment: 'barbell', movementPattern: 'push', instructions: 'Lie on bench, grip bar slightly wider than shoulder-width, lower to chest, press up.' },
  { id: 'incline-bench', name: 'Incline Barbell Bench Press', primaryMuscles: ['chest'], secondaryMuscles: ['shoulders', 'triceps'], equipment: 'barbell', movementPattern: 'push', instructions: 'Set bench to 30-45°. Lower bar to upper chest, press up.' },
  { id: 'decline-bench', name: 'Decline Barbell Bench Press', primaryMuscles: ['chest'], secondaryMuscles: ['triceps'], equipment: 'barbell', movementPattern: 'push', instructions: 'Set bench to -15 to -30°. Lower bar to lower chest, press up.' },
  { id: 'db-bench', name: 'Dumbbell Bench Press', primaryMuscles: ['chest'], secondaryMuscles: ['shoulders', 'triceps'], equipment: 'dumbbell', movementPattern: 'push', instructions: 'Lie on bench with dumbbells at chest height, press up and together.' },
  { id: 'db-incline', name: 'Incline Dumbbell Press', primaryMuscles: ['chest'], secondaryMuscles: ['shoulders', 'triceps'], equipment: 'dumbbell', movementPattern: 'push', instructions: 'Incline bench 30-45°, press dumbbells from chest height.' },
  { id: 'db-flye', name: 'Dumbbell Flye', primaryMuscles: ['chest'], secondaryMuscles: ['shoulders'], equipment: 'dumbbell', movementPattern: 'push', instructions: 'Lie on bench, arms wide with slight elbow bend, arc dumbbells together over chest.' },
  { id: 'cable-crossover', name: 'Cable Crossover', primaryMuscles: ['chest'], secondaryMuscles: ['shoulders'], equipment: 'cable', movementPattern: 'push', instructions: 'Stand between high cable pulleys, bring handles together in front of chest.' },
  { id: 'pec-deck', name: 'Pec Deck / Machine Flye', primaryMuscles: ['chest'], secondaryMuscles: [], equipment: 'machine', movementPattern: 'push', instructions: 'Sit in machine, press pads together in front of chest.' },
  { id: 'pushup', name: 'Push-Up', primaryMuscles: ['chest'], secondaryMuscles: ['shoulders', 'triceps', 'core'], equipment: 'bodyweight', movementPattern: 'push', instructions: 'Hands shoulder-width, body straight, lower chest to floor, press up.' },
  { id: 'dips-chest', name: 'Chest Dips', primaryMuscles: ['chest'], secondaryMuscles: ['triceps', 'shoulders'], equipment: 'bodyweight', movementPattern: 'push', instructions: 'Lean forward on parallel bars, lower until arms at 90°, press up.' },
  // ─── Back ───────────────────────────────────────────────────────────────────
  { id: 'deadlift', name: 'Conventional Deadlift', primaryMuscles: ['back'], secondaryMuscles: ['hamstrings', 'glutes', 'core'], equipment: 'barbell', movementPattern: 'hinge', instructions: 'Hip-width stance, grip bar, flat back, drive hips forward to stand.' },
  { id: 'rdl', name: 'Romanian Deadlift', primaryMuscles: ['hamstrings'], secondaryMuscles: ['back', 'glutes'], equipment: 'barbell', movementPattern: 'hinge', instructions: 'Soft knee bend, hinge at hips pushing them back, bar stays close to legs.' },
  { id: 'barbell-row', name: 'Barbell Bent-Over Row', primaryMuscles: ['back'], secondaryMuscles: ['biceps', 'shoulders'], equipment: 'barbell', movementPattern: 'pull', instructions: 'Hinge 45°, overhand grip, row bar to lower chest.' },
  { id: 'pendlay-row', name: 'Pendlay Row', primaryMuscles: ['back'], secondaryMuscles: ['biceps'], equipment: 'barbell', movementPattern: 'pull', instructions: 'Bar starts on floor each rep, horizontal torso, explosive pull to chest.' },
  { id: 'tbar-row', name: 'T-Bar Row', primaryMuscles: ['back'], secondaryMuscles: ['biceps'], equipment: 'barbell', movementPattern: 'pull', instructions: 'Straddle bar, grip handle, row to lower chest with neutral grip.' },
  { id: 'pullup', name: 'Pull-Up', primaryMuscles: ['back'], secondaryMuscles: ['biceps', 'core'], equipment: 'bodyweight', movementPattern: 'pull', instructions: 'Overhand grip, pull chest to bar, lower under control.' },
  { id: 'chinup', name: 'Chin-Up', primaryMuscles: ['back'], secondaryMuscles: ['biceps'], equipment: 'bodyweight', movementPattern: 'pull', instructions: 'Underhand grip, pull chest to bar.' },
  { id: 'lat-pulldown', name: 'Lat Pulldown', primaryMuscles: ['back'], secondaryMuscles: ['biceps'], equipment: 'cable', movementPattern: 'pull', instructions: 'Wide overhand grip, pull bar to upper chest, squeeze lats.' },
  { id: 'seated-cable-row', name: 'Seated Cable Row', primaryMuscles: ['back'], secondaryMuscles: ['biceps'], equipment: 'cable', movementPattern: 'pull', instructions: 'Sit upright, row handle to lower chest, squeeze shoulder blades.' },
  { id: 'single-arm-row', name: 'Single-Arm Dumbbell Row', primaryMuscles: ['back'], secondaryMuscles: ['biceps'], equipment: 'dumbbell', movementPattern: 'pull', instructions: 'Support on bench, row dumbbell to hip, elbow past torso.' },
  { id: 'face-pull', name: 'Face Pull', primaryMuscles: ['shoulders'], secondaryMuscles: ['back'], equipment: 'cable', movementPattern: 'pull', instructions: 'High cable with rope, pull to face with elbows flared out.' },
  { id: 'good-morning', name: 'Good Morning', primaryMuscles: ['hamstrings'], secondaryMuscles: ['back', 'glutes'], equipment: 'barbell', movementPattern: 'hinge', instructions: 'Bar on traps, soft knee bend, hinge forward at hips.' },
  // ─── Shoulders ──────────────────────────────────────────────────────────────
  { id: 'ohp', name: 'Overhead Press (OHP)', primaryMuscles: ['shoulders'], secondaryMuscles: ['triceps', 'core'], equipment: 'barbell', movementPattern: 'push', instructions: 'From front rack, press bar overhead, lock out, re-rack.' },
  { id: 'db-shoulder-press', name: 'Dumbbell Shoulder Press', primaryMuscles: ['shoulders'], secondaryMuscles: ['triceps'], equipment: 'dumbbell', movementPattern: 'push', instructions: 'Dumbbells at ear height, press overhead.' },
  { id: 'lateral-raise', name: 'Lateral Raise', primaryMuscles: ['shoulders'], secondaryMuscles: [], equipment: 'dumbbell', movementPattern: 'push', instructions: 'Arms slightly bent, raise to shoulder height, lower under control.' },
  { id: 'front-raise', name: 'Front Raise', primaryMuscles: ['shoulders'], secondaryMuscles: [], equipment: 'dumbbell', movementPattern: 'push', instructions: 'Arms straight, raise to shoulder height in front.' },
  { id: 'reverse-flye', name: 'Reverse Flye', primaryMuscles: ['shoulders'], secondaryMuscles: ['back'], equipment: 'dumbbell', movementPattern: 'pull', instructions: 'Bend forward 45°, arms wide, raise dumbbells to sides.' },
  { id: 'arnold-press', name: 'Arnold Press', primaryMuscles: ['shoulders'], secondaryMuscles: ['triceps'], equipment: 'dumbbell', movementPattern: 'push', instructions: 'Start with palms facing you, rotate outward while pressing overhead.' },
  { id: 'upright-row', name: 'Upright Row', primaryMuscles: ['shoulders'], secondaryMuscles: ['biceps', 'back'], equipment: 'barbell', movementPattern: 'pull', instructions: 'Narrow grip, pull bar to chin with elbows leading.' },
  // ─── Biceps ─────────────────────────────────────────────────────────────────
  { id: 'barbell-curl', name: 'Barbell Curl', primaryMuscles: ['biceps'], secondaryMuscles: ['forearms'], equipment: 'barbell', movementPattern: 'pull', instructions: 'Underhand grip, curl bar to chin, lower under control.' },
  { id: 'db-curl', name: 'Dumbbell Curl', primaryMuscles: ['biceps'], secondaryMuscles: ['forearms'], equipment: 'dumbbell', movementPattern: 'pull', instructions: 'Alternate or simultaneous, supinate wrist at top.' },
  { id: 'hammer-curl', name: 'Hammer Curl', primaryMuscles: ['biceps'], secondaryMuscles: ['forearms'], equipment: 'dumbbell', movementPattern: 'pull', instructions: 'Neutral grip (palms facing each other), curl to shoulder.' },
  { id: 'preacher-curl', name: 'Preacher Curl', primaryMuscles: ['biceps'], secondaryMuscles: [], equipment: 'barbell', movementPattern: 'pull', instructions: 'Arms on preacher pad, curl bar or dumbbell to chin.' },
  { id: 'cable-curl', name: 'Cable Curl', primaryMuscles: ['biceps'], secondaryMuscles: [], equipment: 'cable', movementPattern: 'pull', instructions: 'Low cable, curl bar or rope to chin maintaining constant tension.' },
  { id: 'incline-db-curl', name: 'Incline Dumbbell Curl', primaryMuscles: ['biceps'], secondaryMuscles: [], equipment: 'dumbbell', movementPattern: 'pull', instructions: 'Lean back on incline bench, full stretch at bottom, curl up.' },
  // ─── Triceps ─────────────────────────────────────────────────────────────────
  { id: 'skull-crusher', name: 'Skull Crusher', primaryMuscles: ['triceps'], secondaryMuscles: [], equipment: 'barbell', movementPattern: 'push', instructions: 'Lie on bench, bar held above forehead, lower to skull, extend up.' },
  { id: 'tricep-pushdown', name: 'Tricep Pushdown', primaryMuscles: ['triceps'], secondaryMuscles: [], equipment: 'cable', movementPattern: 'push', instructions: 'High cable with bar or rope, push down until arms extended.' },
  { id: 'overhead-tricep', name: 'Overhead Tricep Extension', primaryMuscles: ['triceps'], secondaryMuscles: [], equipment: 'dumbbell', movementPattern: 'push', instructions: 'Hold dumbbell overhead with both hands, lower behind head, extend.' },
  { id: 'close-grip-bench', name: 'Close-Grip Bench Press', primaryMuscles: ['triceps'], secondaryMuscles: ['chest'], equipment: 'barbell', movementPattern: 'push', instructions: 'Hands shoulder-width, elbows tucked, lower and press.' },
  { id: 'dips-tricep', name: 'Tricep Dips', primaryMuscles: ['triceps'], secondaryMuscles: ['chest', 'shoulders'], equipment: 'bodyweight', movementPattern: 'push', instructions: 'Upright torso on parallel bars, lower and press.' },
  // ─── Legs ────────────────────────────────────────────────────────────────────
  { id: 'squat', name: 'Barbell Back Squat', primaryMuscles: ['quads'], secondaryMuscles: ['glutes', 'hamstrings', 'core'], equipment: 'barbell', movementPattern: 'squat', instructions: 'Bar on traps, feet shoulder-width, squat below parallel, drive up.' },
  { id: 'front-squat', name: 'Front Squat', primaryMuscles: ['quads'], secondaryMuscles: ['core', 'glutes'], equipment: 'barbell', movementPattern: 'squat', instructions: 'Bar in front rack, elbows high, squat deep, stay upright.' },
  { id: 'goblet-squat', name: 'Goblet Squat', primaryMuscles: ['quads'], secondaryMuscles: ['glutes', 'core'], equipment: 'kettlebell', movementPattern: 'squat', instructions: 'Hold kettlebell at chest, squat deep, elbows inside knees.' },
  { id: 'leg-press', name: 'Leg Press', primaryMuscles: ['quads'], secondaryMuscles: ['glutes', 'hamstrings'], equipment: 'machine', movementPattern: 'squat', instructions: 'Feet shoulder-width on platform, lower until 90° knees, press up.' },
  { id: 'hack-squat', name: 'Hack Squat', primaryMuscles: ['quads'], secondaryMuscles: ['glutes'], equipment: 'machine', movementPattern: 'squat', instructions: 'Shoulder pads in position, squat deep, drive through heels.' },
  { id: 'lunge', name: 'Barbell Lunge', primaryMuscles: ['quads'], secondaryMuscles: ['glutes', 'hamstrings'], equipment: 'barbell', movementPattern: 'squat', instructions: 'Bar on traps, step forward, lower back knee toward floor.' },
  { id: 'bulgarian-split', name: 'Bulgarian Split Squat', primaryMuscles: ['quads'], secondaryMuscles: ['glutes', 'hamstrings'], equipment: 'dumbbell', movementPattern: 'squat', instructions: 'Rear foot elevated, lunge down until front thigh parallel.' },
  { id: 'hip-thrust', name: 'Barbell Hip Thrust', primaryMuscles: ['glutes'], secondaryMuscles: ['hamstrings'], equipment: 'barbell', movementPattern: 'hinge', instructions: 'Shoulders on bench, bar over hips, drive hips up and squeeze glutes.' },
  { id: 'leg-curl', name: 'Leg Curl', primaryMuscles: ['hamstrings'], secondaryMuscles: [], equipment: 'machine', movementPattern: 'hinge', instructions: 'Lie prone on machine, curl heels to glutes.' },
  { id: 'leg-extension', name: 'Leg Extension', primaryMuscles: ['quads'], secondaryMuscles: [], equipment: 'machine', movementPattern: 'squat', instructions: 'Sit in machine, extend legs to full lockout.' },
  { id: 'calf-raise', name: 'Standing Calf Raise', primaryMuscles: ['calves'], secondaryMuscles: [], equipment: 'machine', movementPattern: 'push', instructions: 'Stand on platform, rise onto toes, lower fully.' },
  { id: 'seated-calf', name: 'Seated Calf Raise', primaryMuscles: ['calves'], secondaryMuscles: [], equipment: 'machine', movementPattern: 'push', instructions: 'Sit with pads on thighs, raise heels as high as possible.' },
  { id: 'sumo-deadlift', name: 'Sumo Deadlift', primaryMuscles: ['glutes'], secondaryMuscles: ['hamstrings', 'back', 'quads'], equipment: 'barbell', movementPattern: 'hinge', instructions: 'Wide stance, toes flared, grip narrow, drive through heels.' },
  // ─── Core ────────────────────────────────────────────────────────────────────
  { id: 'plank', name: 'Plank', primaryMuscles: ['core'], secondaryMuscles: [], equipment: 'bodyweight', movementPattern: 'carry', instructions: 'Forearms on floor, body straight, hold position.' },
  { id: 'ab-rollout', name: 'Ab Wheel Rollout', primaryMuscles: ['core'], secondaryMuscles: ['shoulders'], equipment: 'other', movementPattern: 'carry', instructions: 'On knees, roll wheel forward, extend, return under control.' },
  { id: 'cable-crunch', name: 'Cable Crunch', primaryMuscles: ['core'], secondaryMuscles: [], equipment: 'cable', movementPattern: 'rotation', instructions: 'Kneel under high cable with rope, crunch elbows to thighs.' },
  { id: 'hanging-knee-raise', name: 'Hanging Knee Raise', primaryMuscles: ['core'], secondaryMuscles: [], equipment: 'bodyweight', movementPattern: 'carry', instructions: 'Hang from bar, bring knees to chest under control.' },
  { id: 'russian-twist', name: 'Russian Twist', primaryMuscles: ['core'], secondaryMuscles: [], equipment: 'bodyweight', movementPattern: 'rotation', instructions: 'Sit with knees bent, lean back slightly, rotate side to side.' },
  { id: 'dead-bug', name: 'Dead Bug', primaryMuscles: ['core'], secondaryMuscles: [], equipment: 'bodyweight', movementPattern: 'carry', instructions: 'On back, extend opposite arm/leg while keeping lower back pressed down.' },
  // ─── Olympic / Compound ───────────────────────────────────────────────────────
  { id: 'power-clean', name: 'Power Clean', primaryMuscles: ['full_body'], secondaryMuscles: ['back', 'shoulders', 'quads'], equipment: 'barbell', movementPattern: 'hinge', instructions: 'Pull bar from floor with explosive hip extension, catch in front rack.' },
  { id: 'snatch', name: 'Barbell Snatch', primaryMuscles: ['full_body'], secondaryMuscles: ['back', 'shoulders', 'quads'], equipment: 'barbell', movementPattern: 'hinge', instructions: 'Wide grip, explosive pull, receive bar overhead in squat.' },
  { id: 'clean-and-jerk', name: 'Clean & Jerk', primaryMuscles: ['full_body'], secondaryMuscles: ['back', 'shoulders', 'quads'], equipment: 'barbell', movementPattern: 'hinge', instructions: 'Clean to front rack, then jerk overhead.' },
  { id: 'thruster', name: 'Thruster', primaryMuscles: ['full_body'], secondaryMuscles: ['quads', 'shoulders'], equipment: 'barbell', movementPattern: 'squat', instructions: 'Front squat into push press in one fluid motion.' },
  // ─── Cardio ───────────────────────────────────────────────────────────────────
  { id: 'running', name: 'Running', primaryMuscles: ['cardio'], secondaryMuscles: ['quads', 'hamstrings', 'calves'], equipment: 'other', movementPattern: 'cardio', instructions: 'Track distance and duration.' },
  { id: 'cycling', name: 'Cycling', primaryMuscles: ['cardio'], secondaryMuscles: ['quads'], equipment: 'other', movementPattern: 'cardio', instructions: 'Track duration and resistance.' },
  { id: 'rowing', name: 'Rowing (Erg)', primaryMuscles: ['cardio'], secondaryMuscles: ['back', 'core'], equipment: 'machine', movementPattern: 'cardio', instructions: 'Drive with legs, lean back, pull handle to lower chest.' },
  { id: 'jump-rope', name: 'Jump Rope', primaryMuscles: ['cardio'], secondaryMuscles: ['calves', 'shoulders'], equipment: 'other', movementPattern: 'cardio', instructions: 'Track rounds or duration.' },
  { id: 'burpee', name: 'Burpee', primaryMuscles: ['full_body'], secondaryMuscles: ['cardio'], equipment: 'bodyweight', movementPattern: 'cardio', instructions: 'Drop to floor, push up, jump feet in, jump overhead.' },
  { id: 'battle-ropes', name: 'Battle Ropes', primaryMuscles: ['shoulders'], secondaryMuscles: ['core', 'cardio'], equipment: 'other', movementPattern: 'cardio', instructions: 'Alternate waves or slam patterns for duration.' },
];

export const WORKOUT_TEMPLATES = [
  {
    id: 'stronglifts-5x5',
    name: '5×5 Strength',
    description: 'Classic linear progression. Alternate Workout A and B.',
    isPreloaded: true,
    exercises: [
      { exerciseId: 'squat', defaultSets: 5, defaultReps: 5, restSeconds: 180 },
      { exerciseId: 'bench-press', defaultSets: 5, defaultReps: 5, restSeconds: 180 },
      { exerciseId: 'barbell-row', defaultSets: 5, defaultReps: 5, restSeconds: 180 },
    ],
  },
  {
    id: 'upper-lower',
    name: 'Upper / Lower Split',
    description: '4-day split alternating upper and lower body.',
    isPreloaded: true,
    exercises: [
      { exerciseId: 'bench-press', defaultSets: 4, defaultReps: 8, restSeconds: 120 },
      { exerciseId: 'barbell-row', defaultSets: 4, defaultReps: 8, restSeconds: 120 },
      { exerciseId: 'ohp', defaultSets: 3, defaultReps: 10, restSeconds: 90 },
      { exerciseId: 'lat-pulldown', defaultSets: 3, defaultReps: 10, restSeconds: 90 },
      { exerciseId: 'db-curl', defaultSets: 3, defaultReps: 12, restSeconds: 60 },
      { exerciseId: 'tricep-pushdown', defaultSets: 3, defaultReps: 12, restSeconds: 60 },
    ],
  },
  {
    id: 'push',
    name: 'Push Day (PPL)',
    description: 'Chest, shoulders, and triceps.',
    isPreloaded: true,
    exercises: [
      { exerciseId: 'bench-press', defaultSets: 4, defaultReps: 8, restSeconds: 120 },
      { exerciseId: 'incline-bench', defaultSets: 3, defaultReps: 10, restSeconds: 90 },
      { exerciseId: 'ohp', defaultSets: 3, defaultReps: 10, restSeconds: 90 },
      { exerciseId: 'lateral-raise', defaultSets: 3, defaultReps: 15, restSeconds: 60 },
      { exerciseId: 'tricep-pushdown', defaultSets: 3, defaultReps: 12, restSeconds: 60 },
      { exerciseId: 'skull-crusher', defaultSets: 3, defaultReps: 10, restSeconds: 60 },
    ],
  },
  {
    id: 'pull',
    name: 'Pull Day (PPL)',
    description: 'Back and biceps.',
    isPreloaded: true,
    exercises: [
      { exerciseId: 'deadlift', defaultSets: 3, defaultReps: 5, restSeconds: 180 },
      { exerciseId: 'pullup', defaultSets: 4, defaultReps: 8, restSeconds: 120 },
      { exerciseId: 'barbell-row', defaultSets: 3, defaultReps: 10, restSeconds: 90 },
      { exerciseId: 'seated-cable-row', defaultSets: 3, defaultReps: 12, restSeconds: 90 },
      { exerciseId: 'barbell-curl', defaultSets: 3, defaultReps: 12, restSeconds: 60 },
      { exerciseId: 'hammer-curl', defaultSets: 3, defaultReps: 12, restSeconds: 60 },
    ],
  },
  {
    id: 'legs',
    name: 'Leg Day (PPL)',
    description: 'Quads, hamstrings, glutes, calves.',
    isPreloaded: true,
    exercises: [
      { exerciseId: 'squat', defaultSets: 4, defaultReps: 8, restSeconds: 180 },
      { exerciseId: 'rdl', defaultSets: 3, defaultReps: 10, restSeconds: 120 },
      { exerciseId: 'leg-press', defaultSets: 3, defaultReps: 12, restSeconds: 90 },
      { exerciseId: 'leg-curl', defaultSets: 3, defaultReps: 12, restSeconds: 90 },
      { exerciseId: 'bulgarian-split', defaultSets: 3, defaultReps: 10, restSeconds: 90 },
      { exerciseId: 'calf-raise', defaultSets: 4, defaultReps: 15, restSeconds: 60 },
    ],
  },
  {
    id: 'full-body',
    name: 'Full Body',
    description: 'Hit every muscle group in one session.',
    isPreloaded: true,
    exercises: [
      { exerciseId: 'squat', defaultSets: 3, defaultReps: 8, restSeconds: 120 },
      { exerciseId: 'bench-press', defaultSets: 3, defaultReps: 8, restSeconds: 120 },
      { exerciseId: 'deadlift', defaultSets: 3, defaultReps: 5, restSeconds: 180 },
      { exerciseId: 'ohp', defaultSets: 3, defaultReps: 8, restSeconds: 120 },
      { exerciseId: 'barbell-row', defaultSets: 3, defaultReps: 8, restSeconds: 120 },
      { exerciseId: 'plank', defaultSets: 3, defaultReps: 1, restSeconds: 60 },
    ],
  },
];

export const MUSCLE_GROUPS = [
  { id: 'chest', label: 'Chest' },
  { id: 'back', label: 'Back' },
  { id: 'shoulders', label: 'Shoulders' },
  { id: 'biceps', label: 'Biceps' },
  { id: 'triceps', label: 'Triceps' },
  { id: 'forearms', label: 'Forearms' },
  { id: 'core', label: 'Core' },
  { id: 'quads', label: 'Quads' },
  { id: 'hamstrings', label: 'Hamstrings' },
  { id: 'glutes', label: 'Glutes' },
  { id: 'calves', label: 'Calves' },
  { id: 'full_body', label: 'Full Body' },
  { id: 'cardio', label: 'Cardio' },
] as const;

export const EQUIPMENT_TYPES = [
  { id: 'barbell', label: 'Barbell' },
  { id: 'dumbbell', label: 'Dumbbell' },
  { id: 'cable', label: 'Cable' },
  { id: 'machine', label: 'Machine' },
  { id: 'bodyweight', label: 'Bodyweight' },
  { id: 'kettlebell', label: 'Kettlebell' },
  { id: 'band', label: 'Band' },
  { id: 'smith', label: 'Smith Machine' },
  { id: 'other', label: 'Other' },
] as const;
